name: Build M

on:
  push:
    branches: main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.config.distro }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        config:
          - distro: ubuntu-latest
          - distro: windows-latest
          - distro: macos-11

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build artifact
        id: build
        with:
          distro: ${{ matrix.config.distro }}
        run:
          echo "build starting"
