name: Build M

on:
  push:
    branches: main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }}

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
          - arch: aarch64
            distro: windows_latest
            
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      
