name: Build M

on:
  push:
    branches: main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 16
        architecture:
          - x64
        go-version:
          - 1.16
          - 1.17
    name: Build on ${{ matrix.architecture }} ${{ matrix.os }} with compiler Go v${{ matrix.go-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Install compiler Go 
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: echo "make test"
      
